- name: Install i3 
  become: true
  apt:
    name=i3 
  tags:
    - install
    - core

- name: Install i3blocks 
  become: true
  apt:
    name=i3blocks 
  tags:
    - install
    - core

- name: Install system packages
  become: true
  apt:
    name: ["blueman", "arandr", "autorandr", "pavucontrol", "playerctl", "brightnessctl"]
  tags:
    - install
    - core

- name: Change brightnessctl permissions 
  become: true
  shell: chmod +s $(which brightnessctl) 
  tags:
    - install
    - core

- name: Install neovim dependencies
  become: true
  apt:
    name: ["build-essential", "ninja-build", "gettext", "cmake", "curl", "unzip", "python3.10-venv"]
  tags:
    - install
    - core
    - neovim

- name: Install utilities 
  become: true
  apt:
    name: ["feh", "compton", "maim"]
  tags:
    - install
    - core
    - neovim
