- name: Install i3 
  become: true
  apt:
    name=i3 
  tags:
    - install
    - core
- name: Install system packages
  become: true
  apt:
    name: ["blueman", "arandr", "autorandr"]
  tags:
    - install
    - core
