- name: Install i3 
  become: true
  apt:
    name=i3 
  tags:
    - install
    - core
- name: Install system packages
  become: true
  apt:
    name: ["blueman", "arandr", "autorandr"]
  tags:
    - install
    - core
- name: Install neovim dependencies
  become: true
  apt:
    name: ["build-essential", "ninja-build", "gettext", "cmake", "curl", "unzip", "python3.10-venv", "feh"]
  tags:
    - install
    - core
    - neovim
