- name: Install packages
  become: true
  apt:
    name: [ "tmux", "fzf", "xclip", "tldr", "ripgrep", "fd-find", "gimp" ]
  tags:
    - install
    - productivity

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"
  tags:
    - install
    - productivity
